package me.yejy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK.
 */
public class Book {

    private Long id;
    /** Not-null value. */
    private String bookName;
    private int bookImage;
    /** Not-null value. */
    private String url;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String bookName, int bookImage, String url) {
        this.id = id;
        this.bookName = bookName;
        this.bookImage = bookImage;
        this.url = url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBookName() {
        return bookName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public int getBookImage() {
        return bookImage;
    }

    public void setBookImage(int bookImage) {
        this.bookImage = bookImage;
    }

    /** Not-null value. */
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(String url) {
        this.url = url;
    }

}
