package me.yejy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table COLLECT_VIDEO_ID.
 */
public class CollectVideoId {

    private Long id;

    public CollectVideoId() {
    }

    public CollectVideoId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
