package me.yejy.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.yejy.greendao.Book;
import me.yejy.greendao.VideoIntegral;
import me.yejy.greendao.PayVideoId;
import me.yejy.greendao.CollectVideoId;

import me.yejy.greendao.BookDao;
import me.yejy.greendao.VideoIntegralDao;
import me.yejy.greendao.PayVideoIdDao;
import me.yejy.greendao.CollectVideoIdDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig videoIntegralDaoConfig;
    private final DaoConfig payVideoIdDaoConfig;
    private final DaoConfig collectVideoIdDaoConfig;

    private final BookDao bookDao;
    private final VideoIntegralDao videoIntegralDao;
    private final PayVideoIdDao payVideoIdDao;
    private final CollectVideoIdDao collectVideoIdDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        videoIntegralDaoConfig = daoConfigMap.get(VideoIntegralDao.class).clone();
        videoIntegralDaoConfig.initIdentityScope(type);

        payVideoIdDaoConfig = daoConfigMap.get(PayVideoIdDao.class).clone();
        payVideoIdDaoConfig.initIdentityScope(type);

        collectVideoIdDaoConfig = daoConfigMap.get(CollectVideoIdDao.class).clone();
        collectVideoIdDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        videoIntegralDao = new VideoIntegralDao(videoIntegralDaoConfig, this);
        payVideoIdDao = new PayVideoIdDao(payVideoIdDaoConfig, this);
        collectVideoIdDao = new CollectVideoIdDao(collectVideoIdDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(VideoIntegral.class, videoIntegralDao);
        registerDao(PayVideoId.class, payVideoIdDao);
        registerDao(CollectVideoId.class, collectVideoIdDao);
    }
    
    public void clear() {
        bookDaoConfig.getIdentityScope().clear();
        videoIntegralDaoConfig.getIdentityScope().clear();
        payVideoIdDaoConfig.getIdentityScope().clear();
        collectVideoIdDaoConfig.getIdentityScope().clear();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public VideoIntegralDao getVideoIntegralDao() {
        return videoIntegralDao;
    }

    public PayVideoIdDao getPayVideoIdDao() {
        return payVideoIdDao;
    }

    public CollectVideoIdDao getCollectVideoIdDao() {
        return collectVideoIdDao;
    }

}
