package me.yejy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PAY_VIDEO_ID.
 */
public class PayVideoId {

    private Long id;

    public PayVideoId() {
    }

    public PayVideoId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
