package me.yejy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table VIDEO_INTEGRAL.
 */
public class VideoIntegral implements Serializable{

    private Long id;
    /** Not-null value. */
    private String video_name;
    private String video_zip;
    private String video_describe;
    private Integer video_style;
    private String video_price;
    private String see_num;
    private String evaluate_num;
    private String collect_num;
    /** Not-null value. */
    private String video_url;
    private Long video_addtime;
    private Integer cate_id;
    private String video_jifen;

    public VideoIntegral() {
    }

    public VideoIntegral(Long id) {
        this.id = id;
    }

    public VideoIntegral(Long id, String video_name, String video_zip, String video_describe, Integer video_style, String video_price, String see_num, String evaluate_num, String collect_num, String video_url, Long video_addtime, Integer cate_id, String video_jifen) {
        this.id = id;
        this.video_name = video_name;
        this.video_zip = video_zip;
        this.video_describe = video_describe;
        this.video_style = video_style;
        this.video_price = video_price;
        this.see_num = see_num;
        this.evaluate_num = evaluate_num;
        this.collect_num = collect_num;
        this.video_url = video_url;
        this.video_addtime = video_addtime;
        this.cate_id = cate_id;
        this.video_jifen = video_jifen;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getVideo_name() {
        return video_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideo_name(String video_name) {
        this.video_name = video_name;
    }

    public String getVideo_zip() {
        return video_zip;
    }

    public void setVideo_zip(String video_zip) {
        this.video_zip = video_zip;
    }

    public String getVideo_describe() {
        return video_describe;
    }

    public void setVideo_describe(String video_describe) {
        this.video_describe = video_describe;
    }

    public Integer getVideo_style() {
        return video_style;
    }

    public void setVideo_style(Integer video_style) {
        this.video_style = video_style;
    }

    public String getVideo_price() {
        return video_price;
    }

    public void setVideo_price(String video_price) {
        this.video_price = video_price;
    }

    public String getSee_num() {
        return see_num;
    }

    public void setSee_num(String see_num) {
        this.see_num = see_num;
    }

    public String getEvaluate_num() {
        return evaluate_num;
    }

    public void setEvaluate_num(String evaluate_num) {
        this.evaluate_num = evaluate_num;
    }

    public String getCollect_num() {
        return collect_num;
    }

    public void setCollect_num(String collect_num) {
        this.collect_num = collect_num;
    }

    /** Not-null value. */
    public String getVideo_url() {
        return video_url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setVideo_url(String video_url) {
        this.video_url = video_url;
    }

    public Long getVideo_addtime() {
        return video_addtime;
    }

    public void setVideo_addtime(Long video_addtime) {
        this.video_addtime = video_addtime;
    }

    public Integer getCate_id() {
        return cate_id;
    }

    public void setCate_id(Integer cate_id) {
        this.cate_id = cate_id;
    }

    public String getVideo_jifen() {
        return video_jifen;
    }

    public void setVideo_jifen(String video_jifen) {
        this.video_jifen = video_jifen;
    }

}
